site_name: My Tools
repo_name: julienpillaud/tools
repo_url: https://github.com/julienpillaud/tools
theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: blue

    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: deep purple
      accent: blue
