[project]
name = "tools"
version = "0.0.0"
requires-python = ">=3.12"
dependencies = [
    "typer>=0.13.0",
]

[dependency-groups]
dev = [
    "mypy>=1.13.0",
    "pre-commit>=4.0.1",
    "ruff>=0.7.4",
]
